import { ChestSpritePaths, ChestSpriteSecondaries } from './chest-sprites.const.js';
import { SpriteOffset } from './sprite-offset.const.js';

export const FeatureSpritePaths = [
  '/tiles/features/barrel.png',
  '/tiles/features/bed_n.png',
  '/tiles/features/bed_e.png',
  '/tiles/features/bed_s.png',
  '/tiles/features/bed_w.png',
  '/tiles/features/bookcase_s.png',
  '/tiles/features/bookcase_w.png',
  '/tiles/features/chair_e.png',
  '/tiles/features/chair_n.png',
  '/tiles/features/chair_s.png',
  '/tiles/features/chair_w.png',
  ...ChestSpritePaths,
  '/tiles/features/fire_shrine.png',
  '/tiles/features/plinth.png',
  '/tiles/features/table_s.png',
  '/tiles/features/table_w.png',
  '/tiles/features/throne_e.png',
  '/tiles/features/throne_n.png',
  '/tiles/features/throne_s.png',
  '/tiles/features/throne_w.png',
  '/tiles/features/tombstone_x.png',
  '/tiles/features/tombstone_y.png',
  '/tiles/features/vase.png',
  '/tiles/features/water_shrine.png',
  '/tiles/features/well.png',
] as const;

export type FeatureSpritePath = (typeof FeatureSpritePaths)[number];

export const FeatureSpriteSecondaries: Record<FeatureSpritePath, SpriteOffset[]> = {
  '/tiles/features/barrel.png': [],
  '/tiles/features/bed_n.png': [
    { x: 0, y: -1 },
    { x: 0, y: -2 },
    { x: 1, y: 0 },
    { x: 1, y: -1 },
    { x: 1, y: -2 },
  ],
  '/tiles/features/bed_e.png': [
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 0, y: -1 },
    { x: 1, y: -1 },
    { x: 2, y: -1 },
  ],
  '/tiles/features/bed_s.png': [
    { x: 0, y: -1 },
    { x: 0, y: -2 },
    { x: 1, y: 0 },
    { x: 1, y: -1 },
    { x: 1, y: -2 },
  ],
  '/tiles/features/bed_w.png': [
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 0, y: -1 },
    { x: 1, y: -1 },
    { x: 2, y: -1 },
  ],
  '/tiles/features/bookcase_s.png': [{ x: 1, y: 0 }],
  '/tiles/features/bookcase_w.png': [{ x: 0, y: -1 }],
  '/tiles/features/chair_e.png': [],
  '/tiles/features/chair_n.png': [],
  '/tiles/features/chair_s.png': [],
  '/tiles/features/chair_w.png': [],
  ...ChestSpriteSecondaries,
  '/tiles/features/fire_shrine.png': [],
  '/tiles/features/plinth.png': [],
  '/tiles/features/table_s.png': [
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 0, y: -1 },
    { x: 1, y: -1 },
    { x: 2, y: -1 },
  ],
  '/tiles/features/table_w.png': [
    { x: 1, y: 0 },
    { x: 2, y: 0 },
    { x: 0, y: -1 },
    { x: 1, y: -1 },
    { x: 2, y: -1 },
  ],
  '/tiles/features/throne_e.png': [],
  '/tiles/features/throne_n.png': [],
  '/tiles/features/throne_s.png': [],
  '/tiles/features/throne_w.png': [],
  '/tiles/features/tombstone_x.png': [],
  '/tiles/features/tombstone_y.png': [],
  '/tiles/features/vase.png': [],
  '/tiles/features/water_shrine.png': [],
  '/tiles/features/well.png': [],
} as const;
