export const HeroSpritePaths = [
  '/tiles/heroes/barbarian_male_n.png',
  '/tiles/heroes/barbarian_male_e.png',
  '/tiles/heroes/barbarian_male_s.png',
  '/tiles/heroes/barbarian_male_w.png',
  '/tiles/heroes/barbarian_female_n.png',
  '/tiles/heroes/barbarian_female_e.png',
  '/tiles/heroes/barbarian_female_s.png',
  '/tiles/heroes/barbarian_female_w.png',
  '/tiles/heroes/dwarf_male_n.png',
  '/tiles/heroes/dwarf_male_e.png',
  '/tiles/heroes/dwarf_male_s.png',
  '/tiles/heroes/dwarf_male_w.png',
  '/tiles/heroes/dwarf_female_n.png',
  '/tiles/heroes/dwarf_female_e.png',
  '/tiles/heroes/dwarf_female_s.png',
  '/tiles/heroes/dwarf_female_w.png',
  '/tiles/heroes/elf_male_n.png',
  '/tiles/heroes/elf_male_e.png',
  '/tiles/heroes/elf_male_s.png',
  '/tiles/heroes/elf_male_w.png',
  '/tiles/heroes/elf_female_n.png',
  '/tiles/heroes/elf_female_e.png',
  '/tiles/heroes/elf_female_s.png',
  '/tiles/heroes/elf_female_w.png',
  '/tiles/heroes/wizard_male_n.png',
  '/tiles/heroes/wizard_male_e.png',
  '/tiles/heroes/wizard_male_s.png',
  '/tiles/heroes/wizard_male_w.png',
  '/tiles/heroes/wizard_female_n.png',
  '/tiles/heroes/wizard_female_e.png',
  '/tiles/heroes/wizard_female_s.png',
  '/tiles/heroes/wizard_female_w.png',
] as const;

export type HeroSpritePath = (typeof HeroSpritePaths)[number];
