import { FeatureSpritePath, SpriteOffset } from '@hw/shared/sprites';

export const FeatureSpriteSizes: Record<FeatureSpritePath, SpriteOffset> = {
  '/tiles/features/altar_s.png': { x: 144, y: 144 },
  '/tiles/features/altar_w.png': { x: 144, y: 144 },
  '/tiles/features/barrel.png': { x: 64, y: 64 },
  '/tiles/features/bed_n.png': { x: 112, y: 112 },
  '/tiles/features/bed_e.png': { x: 112, y: 112 },
  '/tiles/features/bed_s.png': { x: 112, y: 112 },
  '/tiles/features/bed_w.png': { x: 112, y: 112 },
  '/tiles/features/bookcase_s.png': { x: 128, y: 128 },
  '/tiles/features/bookcase_w.png': { x: 128, y: 128 },
  '/tiles/features/chair_e.png': { x: 64, y: 64 },
  '/tiles/features/chair_n.png': { x: 64, y: 64 },
  '/tiles/features/chair_s.png': { x: 64, y: 64 },
  '/tiles/features/chair_w.png': { x: 64, y: 64 },
  '/tiles/features/closed_chest_s.png': { x: 64, y: 64 },
  '/tiles/features/closed_chest_w.png': { x: 64, y: 64 },
  '/tiles/features/closed_large_chest_s.png': { x: 64, y: 64 },
  '/tiles/features/closed_large_chest_w.png': { x: 64, y: 64 },
  '/tiles/features/open_chest_s.png': { x: 64, y: 64 },
  '/tiles/features/open_chest_w.png': { x: 64, y: 64 },
  '/tiles/features/open_large_chest_s.png': { x: 64, y: 64 },
  '/tiles/features/open_large_chest_w.png': { x: 64, y: 64 },
  '/tiles/features/fire_shrine.png': { x: 64, y: 64 },
  '/tiles/features/plinth.png': { x: 64, y: 64 },
  '/tiles/features/table_s.png': { x: 144, y: 144 },
  '/tiles/features/table_w.png': { x: 144, y: 144 },
  '/tiles/features/throne_e.png': { x: 64, y: 64 },
  '/tiles/features/throne_n.png': { x: 64, y: 64 },
  '/tiles/features/throne_s.png': { x: 64, y: 64 },
  '/tiles/features/throne_w.png': { x: 64, y: 64 },
  '/tiles/features/tombstone_x.png': { x: 64, y: 64 },
  '/tiles/features/tombstone_y.png': { x: 64, y: 64 },
  '/tiles/features/vase.png': { x: 64, y: 64 },
  '/tiles/features/water_shrine.png': { x: 64, y: 64 },
  '/tiles/features/well.png': { x: 64, y: 64 },
} as const;

export const FeatureSpriteOffsets: Record<FeatureSpritePath, SpriteOffset> = {
  '/tiles/features/altar_s.png': { x: 20, y: -53 },
  '/tiles/features/altar_w.png': { x: -20, y: -53 },
  '/tiles/features/barrel.png': { x: 0, y: -32 },
  '/tiles/features/bed_n.png': { x: -16, y: -65 },
  '/tiles/features/bed_e.png': { x: 13, y: -58 },
  '/tiles/features/bed_s.png': { x: -16, y: -65 },
  '/tiles/features/bed_w.png': { x: 13, y: -65 },
  '/tiles/features/bookcase_s.png': { x: 19, y: -54 },
  '/tiles/features/bookcase_w.png': { x: -18, y: -54 },
  '/tiles/features/chair_e.png': { x: -1, y: -30 },
  '/tiles/features/chair_n.png': { x: 0, y: -30 },
  '/tiles/features/chair_s.png': { x: 0, y: -30 },
  '/tiles/features/chair_w.png': { x: 0, y: -32 },
  '/tiles/features/closed_chest_s.png': { x: 0, y: -30 },
  '/tiles/features/closed_chest_w.png': { x: 0, y: -30 },
  '/tiles/features/closed_large_chest_s.png': { x: 15, y: -32 },
  '/tiles/features/closed_large_chest_w.png': { x: -15, y: -32 },
  '/tiles/features/open_chest_s.png': { x: 0, y: -30 },
  '/tiles/features/open_chest_w.png': { x: 0, y: -30 },
  '/tiles/features/open_large_chest_s.png': { x: 15, y: -32 },
  '/tiles/features/open_large_chest_w.png': { x: -15, y: -32 },
  '/tiles/features/fire_shrine.png': { x: 0, y: -37 },
  '/tiles/features/plinth.png': { x: 0, y: -30 },
  '/tiles/features/table_s.png': { x: 12, y: -75 },
  '/tiles/features/table_w.png': { x: -15, y: -73 },
  '/tiles/features/throne_e.png': { x: 0, y: -31 },
  '/tiles/features/throne_n.png': { x: 1, y: -32 },
  '/tiles/features/throne_s.png': { x: -1, y: -33 },
  '/tiles/features/throne_w.png': { x: 0, y: -31 },
  '/tiles/features/tombstone_x.png': { x: 0, y: -30 },
  '/tiles/features/tombstone_y.png': { x: 0, y: -30 },
  '/tiles/features/vase.png': { x: 0, y: -34 },
  '/tiles/features/water_shrine.png': { x: 1, y: -34 },
  '/tiles/features/well.png': { x: -1, y: -32 },
} as const;

export const FeatureSpriteTrappable: Record<FeatureSpritePath, boolean> = {
  '/tiles/features/altar_s.png': false,
  '/tiles/features/altar_w.png': false,
  '/tiles/features/barrel.png': false,
  '/tiles/features/bed_n.png': false,
  '/tiles/features/bed_e.png': false,
  '/tiles/features/bed_s.png': false,
  '/tiles/features/bed_w.png': false,
  '/tiles/features/bookcase_s.png': true,
  '/tiles/features/bookcase_w.png': true,
  '/tiles/features/chair_e.png': false,
  '/tiles/features/chair_n.png': false,
  '/tiles/features/chair_s.png': false,
  '/tiles/features/chair_w.png': false,
  '/tiles/features/closed_chest_s.png': true,
  '/tiles/features/closed_chest_w.png': true,
  '/tiles/features/closed_large_chest_s.png': true,
  '/tiles/features/closed_large_chest_w.png': true,
  '/tiles/features/open_chest_s.png': false,
  '/tiles/features/open_chest_w.png': false,
  '/tiles/features/open_large_chest_s.png': false,
  '/tiles/features/open_large_chest_w.png': false,
  '/tiles/features/fire_shrine.png': false,
  '/tiles/features/plinth.png': false,
  '/tiles/features/table_s.png': false,
  '/tiles/features/table_w.png': false,
  '/tiles/features/throne_e.png': false,
  '/tiles/features/throne_n.png': false,
  '/tiles/features/throne_s.png': false,
  '/tiles/features/throne_w.png': false,
  '/tiles/features/tombstone_x.png': false,
  '/tiles/features/tombstone_y.png': false,
  '/tiles/features/vase.png': false,
  '/tiles/features/water_shrine.png': false,
  '/tiles/features/well.png': false,
} as const;

export const FeatureSpriteZIndex = 5;
