import { MonsterType } from './monster-type.const.js';

const goblinNames = [
  'Snivvik',
  'Grotspike',
  'Fizznak',
  'Wretchwort',
  'Skabble',
  'Nibblewart',
  'Gretch',
  'Snikrat',
  'Pustwick',
  'Zibblefang',
  'Crawlmire',
  'Rotgizz',
  'Sneekwort',
  'Bligsnap',
  'Yellgut',
  'Scabwick',
  'Twitchfang',
  'Muckspore',
  'Gribblewart',
  'Snagrot',
  'Veznik',
  'Pudgeskab',
  'Clawmire',
  'Fetchwort',
  'Drizznak',
  'Blotchwort',
  'Spikegrubb',
  'Reekling',
  'Gnarlfizz',
  'Vomwick the Runt',
];

const orcNames = [
  'Gornak Bloodtusk',
  'Druul',
  'Skargath',
  'Vorruk',
  'Braghul',
  'Throgg',
  'Murgash',
  'Graknor',
  'Bolduk',
  'Vreth',
  'Horgash',
  'Druknol',
  'Skoll',
  'Zurgath',
  'Rhaknor',
  'Gruknash ',
  'Bolg',
  'Drakthar',
  'Urzog',
  'Korruk',
  'Thragnul',
  'Wugrash',
  'Skolvur',
  'Borgash',
  'Drukhnar',
  'Raggorn',
  'Vorguth',
  'Krulag',
  'Narkhul',
  'Ozgrath',
];

export const MonsterNames: Record<MonsterType, string[]> = {
  chaos_mage: ['#PLACEHOLDER chaos_mage'],
  chaos_warrior: ['#PLACEHOLDER chaos_warrior'],
  fimir: ['#PLACEHOLDER fimir'],
  gargoyle: ['#PLACEHOLDER gargoyle'],
  goblin_axe: goblinNames.slice(),
  goblin_dagger: goblinNames.slice(),
  goblin_sword: goblinNames.slice(),
  mummy: ['#PLACEHOLDER mummy'],
  orc_cleaver: orcNames.slice(),
  orc_mace: orcNames.slice(),
  orc_sword: orcNames.slice(),
  skeleton: ['#PLACEHOLDER skeleton'],
  zombie: ['#PLACEHOLDER zombie'],
};
