import { PrismaClient } from '@hw/prismagen/client';
import { HwEditorCell } from '@hw/shared/editor';
import { InputJsonValue } from '@prisma/client/runtime/client';

export async function seedAdventureTemplates(prismaClient: PrismaClient): Promise<void> {
  const sunkenTombCells: HwEditorCell[] = [
    {
      x: 5,
      y: 2,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'n',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_01.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 2,
      spawn: true,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'n',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_02.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 3,
      spawn: true,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'n',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_03.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 3,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'n',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_04.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 4,
      spawn: true,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'n',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_05.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 2,
      spawn: true,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_01.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 1,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_05.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: '/tiles/stairs/stairs_s.png',
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 3,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_04.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 4,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_10.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 4,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_06.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 5,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_04.png',
      door: {
        spritePath: '/tiles/doors/closed_door_y.png',
        trapped: true,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 6,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_08.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 6,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_10.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 6,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_08.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 3,
      y: 6,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_11.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 7,
      y: 6,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: 'goblin_dagger',
        direction: 'w',
        spritePath: '/tiles/monsters/goblin_dagger_w.png',
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_03.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 8,
      y: 6,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: true,
        w: true,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_05.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 8,
      y: 7,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_08.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 7,
      y: 7,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_11.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 7,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_11.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 7,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_12.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 7,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_05.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 3,
      y: 7,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_04.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 8,
      y: 8,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_10.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 7,
      y: 8,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_03.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 8,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_10.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 8,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_11.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 8,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_01.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 3,
      y: 8,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_12.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 8,
      y: 9,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_12.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 7,
      y: 9,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_09.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 9,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_12.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 9,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_08.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 9,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_04.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 3,
      y: 9,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_03.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 8,
      y: 10,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_01.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 7,
      y: 10,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_07.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 6,
      y: 10,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_11.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 5,
      y: 10,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_06.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 4,
      y: 10,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: null,
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_01.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
    {
      x: 3,
      y: 10,
      spawn: false,
      corners: {
        e: false,
        n: false,
        s: false,
        w: false,
      },
      feature: {
        trapped: false,
        spritePath: '/tiles/features/throne_n.png',
      },
      monster: {
        type: null,
        direction: 'w',
        spritePath: null,
      },
      secondary: null,
      baseSpritePath: '/tiles/floors/floor_05.png',
      door: {
        spritePath: null,
        trapped: false,
      },
      stairsSpritePath: null,
      floorTrapSpritePath: null,
    },
  ];

  await prismaClient.adventureTemplate.createMany({
    data: [
      {
        name: 'The Sunken Tomb',
        info: 'Explore the Sunken Tomb!',
        dungeon: { cells: sunkenTombCells as unknown as InputJsonValue },
      },
      { name: 'Raid on Blackmoor Keep', info: 'Raid the Blackmoor Keep!', dungeon: { cells: [] } },
    ],
  });
}
