import { HwItemName } from '../inventory/item-names.const.js';

export const ItemAttackDie: Record<HwItemName, number> = {
  battleaxe: 4,
  broadsword: 3,
  buckler: 0,
  chainmail: 0,
  crossbow: 4,
  dagger: 1,
  goblin_axe: 1,
  goblin_dagger: 1,
  goblin_sword: 1,
  greatsword: 4,
  handaxe: 2,
  healing_potion: 0,
  helmet: 0,
  leather_armor: 0,
  orc_cleaver: 1,
  orc_mace: 1,
  orc_sword: 1,
  padded_armor: 0,
  plate_armor: 0,
  shield: 0,
  shortsword: 1,
  spear: 3,
  staff: 1,
  toolkit: 0,
};

export const ItemDefendDie: Record<HwItemName, number> = {
  battleaxe: 0,
  broadsword: 0,
  buckler: 1,
  chainmail: 3,
  crossbow: 0,
  dagger: 0,
  goblin_axe: 0,
  goblin_dagger: 0,
  goblin_sword: 0,
  greatsword: 0,
  handaxe: 0,
  healing_potion: 0,
  helmet: 1,
  leather_armor: 2,
  orc_cleaver: 0,
  orc_mace: 0,
  orc_sword: 0,
  padded_armor: 1,
  plate_armor: 4,
  shield: 0,
  shortsword: 0,
  spear: 0,
  staff: 0,
  toolkit: 0,
};

export const ItemMovementPoints: Record<HwItemName, number> = {
  battleaxe: 0,
  broadsword: 0,
  buckler: 0,
  chainmail: -1,
  crossbow: 0,
  dagger: 0,
  goblin_axe: 0,
  goblin_dagger: 0,
  goblin_sword: 0,
  greatsword: 0,
  handaxe: 0,
  healing_potion: 0,
  helmet: 0,
  leather_armor: 0,
  orc_cleaver: 0,
  orc_mace: 0,
  orc_sword: 0,
  padded_armor: 0,
  plate_armor: -2,
  shield: 0,
  shortsword: 0,
  spear: 0,
  staff: 0,
  toolkit: 0,
};
