import { HeroSpritePath, SpriteOffset } from '@hw/shared/sprites';
import {
  BlueSpriteTint,
  GreenSpriteTint,
  RedSpriteTint,
  YellowSpriteTint,
} from './sprite-tints.const';

export const HeroSpriteSizes: Record<HeroSpritePath, SpriteOffset> = {
  '/tiles/heroes/barbarian_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_se.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_se.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_se.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_se.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_se.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_se.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_se.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_nw.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_ne.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_se.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_sw.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_nw.png': { x: 60, y: 120 },
} as const;

export const HeroSpriteOffsets: Record<HeroSpritePath, SpriteOffset> = {
  '/tiles/heroes/barbarian_male_n.png': { x: 2, y: -63 },
  '/tiles/heroes/barbarian_male_ne.png': { x: 2, y: -63 },
  '/tiles/heroes/barbarian_male_e.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_se.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_s.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_sw.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_w.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_nw.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_female_n.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_ne.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_e.png': { x: 1, y: -48 },
  '/tiles/heroes/barbarian_female_se.png': { x: 1, y: -48 },
  '/tiles/heroes/barbarian_female_s.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_sw.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_w.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_nw.png': { x: -1, y: -48 },
  '/tiles/heroes/dwarf_male_n.png': { x: -4, y: -31 },
  '/tiles/heroes/dwarf_male_ne.png': { x: -4, y: -31 },
  '/tiles/heroes/dwarf_male_e.png': { x: -3, y: -33 },
  '/tiles/heroes/dwarf_male_se.png': { x: -3, y: -33 },
  '/tiles/heroes/dwarf_male_s.png': { x: 3, y: -34 },
  '/tiles/heroes/dwarf_male_sw.png': { x: 3, y: -34 },
  '/tiles/heroes/dwarf_male_w.png': { x: 3, y: -30 },
  '/tiles/heroes/dwarf_male_nw.png': { x: 3, y: -30 },
  '/tiles/heroes/dwarf_female_n.png': { x: 4, y: -48 },
  '/tiles/heroes/dwarf_female_ne.png': { x: 4, y: -48 },
  '/tiles/heroes/dwarf_female_e.png': { x: -1, y: -46 },
  '/tiles/heroes/dwarf_female_se.png': { x: -1, y: -46 },
  '/tiles/heroes/dwarf_female_s.png': { x: -3, y: -48 },
  '/tiles/heroes/dwarf_female_sw.png': { x: -3, y: -48 },
  '/tiles/heroes/dwarf_female_w.png': { x: -1, y: -47 },
  '/tiles/heroes/dwarf_female_nw.png': { x: -1, y: -47 },
  '/tiles/heroes/elf_male_n.png': { x: 0, y: -44 },
  '/tiles/heroes/elf_male_ne.png': { x: 0, y: -44 },
  '/tiles/heroes/elf_male_e.png': { x: -4, y: -45 },
  '/tiles/heroes/elf_male_se.png': { x: -4, y: -45 },
  '/tiles/heroes/elf_male_s.png': { x: 0, y: -46 },
  '/tiles/heroes/elf_male_sw.png': { x: 0, y: -46 },
  '/tiles/heroes/elf_male_w.png': { x: 5, y: -46 },
  '/tiles/heroes/elf_male_nw.png': { x: 5, y: -46 },
  '/tiles/heroes/elf_female_n.png': { x: -1, y: -54 },
  '/tiles/heroes/elf_female_ne.png': { x: -1, y: -54 },
  '/tiles/heroes/elf_female_e.png': { x: -8, y: -56 },
  '/tiles/heroes/elf_female_se.png': { x: -8, y: -56 },
  '/tiles/heroes/elf_female_s.png': { x: 2, y: -57 },
  '/tiles/heroes/elf_female_sw.png': { x: 2, y: -57 },
  '/tiles/heroes/elf_female_w.png': { x: 7, y: -55 },
  '/tiles/heroes/elf_female_nw.png': { x: 7, y: -55 },
  '/tiles/heroes/wizard_male_n.png': { x: 2, y: -48 },
  '/tiles/heroes/wizard_male_ne.png': { x: 2, y: -48 },
  '/tiles/heroes/wizard_male_e.png': { x: -4, y: -49 },
  '/tiles/heroes/wizard_male_se.png': { x: -4, y: -49 },
  '/tiles/heroes/wizard_male_s.png': { x: -3, y: -50 },
  '/tiles/heroes/wizard_male_sw.png': { x: -3, y: -50 },
  '/tiles/heroes/wizard_male_w.png': { x: 2, y: -49 },
  '/tiles/heroes/wizard_male_nw.png': { x: 2, y: -49 },
  '/tiles/heroes/wizard_female_n.png': { x: -1, y: -38 },
  '/tiles/heroes/wizard_female_ne.png': { x: -1, y: -38 },
  '/tiles/heroes/wizard_female_e.png': { x: 9, y: -36 },
  '/tiles/heroes/wizard_female_se.png': { x: 9, y: -36 },
  '/tiles/heroes/wizard_female_s.png': { x: 0, y: -37 },
  '/tiles/heroes/wizard_female_sw.png': { x: 0, y: -37 },
  '/tiles/heroes/wizard_female_w.png': { x: -6, y: -40 },
  '/tiles/heroes/wizard_female_nw.png': { x: -6, y: -40 },
} as const;

export const HeroSpriteTints: number[] = [
  RedSpriteTint,
  BlueSpriteTint,
  YellowSpriteTint,
  GreenSpriteTint,
];
