import { HeroSpritePath, SpriteOffset } from '@hw/shared/sprites';
import {
  BlueSpriteTint,
  GreenSpriteTint,
  RedSpriteTint,
  YellowSpriteTint,
} from './sprite-tints.const';

export const HeroSpriteSizes: Record<HeroSpritePath, SpriteOffset> = {
  '/tiles/heroes/barbarian_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/barbarian_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/dwarf_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/elf_female_w.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_n.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_e.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_s.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_male_w.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_n.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_e.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_s.png': { x: 60, y: 120 },
  '/tiles/heroes/wizard_female_w.png': { x: 60, y: 120 },
} as const;

export const HeroSpriteOffsets: Record<HeroSpritePath, SpriteOffset> = {
  '/tiles/heroes/barbarian_male_n.png': { x: 2, y: -63 },
  '/tiles/heroes/barbarian_male_e.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_s.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_male_w.png': { x: -1, y: -63 },
  '/tiles/heroes/barbarian_female_n.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_e.png': { x: 1, y: -48 },
  '/tiles/heroes/barbarian_female_s.png': { x: -1, y: -48 },
  '/tiles/heroes/barbarian_female_w.png': { x: -1, y: -48 },
  '/tiles/heroes/dwarf_male_n.png': { x: -4, y: -31 },
  '/tiles/heroes/dwarf_male_e.png': { x: -3, y: -33 },
  '/tiles/heroes/dwarf_male_s.png': { x: 3, y: -34 },
  '/tiles/heroes/dwarf_male_w.png': { x: 3, y: -30 },
  '/tiles/heroes/dwarf_female_n.png': { x: -1, y: -33 },
  '/tiles/heroes/dwarf_female_e.png': { x: -3, y: -33 },
  '/tiles/heroes/dwarf_female_s.png': { x: -1, y: -33 },
  '/tiles/heroes/dwarf_female_w.png': { x: 3, y: -30 },
  '/tiles/heroes/elf_male_n.png': { x: -1, y: -33 },
  '/tiles/heroes/elf_male_e.png': { x: -3, y: -33 },
  '/tiles/heroes/elf_male_s.png': { x: -1, y: -33 },
  '/tiles/heroes/elf_male_w.png': { x: 3, y: -30 },
  '/tiles/heroes/elf_female_n.png': { x: -1, y: -54 },
  '/tiles/heroes/elf_female_e.png': { x: -8, y: -56 },
  '/tiles/heroes/elf_female_s.png': { x: 2, y: -57 },
  '/tiles/heroes/elf_female_w.png': { x: 7, y: -55 },
  '/tiles/heroes/wizard_male_n.png': { x: -1, y: -33 },
  '/tiles/heroes/wizard_male_e.png': { x: -3, y: -33 },
  '/tiles/heroes/wizard_male_s.png': { x: -1, y: -33 },
  '/tiles/heroes/wizard_male_w.png': { x: 3, y: -30 },
  '/tiles/heroes/wizard_female_n.png': { x: -1, y: -33 },
  '/tiles/heroes/wizard_female_e.png': { x: -3, y: -33 },
  '/tiles/heroes/wizard_female_s.png': { x: -1, y: -33 },
  '/tiles/heroes/wizard_female_w.png': { x: 3, y: -30 },
} as const;

export const HeroSpriteTints: number[] = [
  RedSpriteTint,
  BlueSpriteTint,
  YellowSpriteTint,
  GreenSpriteTint,
];
