name: Build and deploy Hot Wizards

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-hw:
    runs-on: ubuntu-latest
    environment: production
    env:
      RELEASE_NAME: '${{ github.sha }}'

    steps:
      - name: Common - Checkout code
        uses: actions/checkout@v6.0.2

      - name: Common - Setup node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '24.14.1'
          cache: 'npm'

      - name: HWBE - Create .env file
        working-directory: hwbe
        run: |
          echo "HWBE_NODE_ENV=${{ vars.HWBE_NODE_ENV }}" >> .env
          echo "HWBE_CORS_ORIGIN=${{ vars.HWBE_CORS_ORIGIN }}" >> .env
          echo "HWBE_PORT=${{ vars.HWBE_PORT }}" >> .env
          echo "HWBE_SENTRY_DSN=${{ secrets.HWBE_SENTRY_DSN }}" >> .env
          echo "HWBE_DB_URL=postgresql://${{ vars.HWBE_DB_USER }}:${{ secrets.HWBE_DB_PASSWORD }}@${{ vars.HWBE_DB_HOST }}:${{ vars.HWBE_DB_PORT }}/${{ vars.HWBE_DB_NAME }}?schema=public" >> .env
          echo "SENTRY_RELEASE=${{ github.sha }}" >> .env

      - name: HWFE - Inject Sentry DSN
        working-directory: hwfe
        run: |
          sed -i "s|HWFE_SENTRY_DSN_PLACEHOLDER|${{ vars.HWFE_SENTRY_DSN }}|" src/environments/environment.ts
          sed -i "s|HWFE_SENTRY_RELEASE_PLACEHOLDER|${{ github.sha }}|" src/environments/environment.ts

      - name: Install and build
        run: |
          npm install
          npm run hwbe:prisma:gen
          npm run hwbe:build
          npm run hwfe:build

      - name: Prepare deployment
        run: |
          mkdir hw
          mv package.json hw
          mv package-lock.json hw
          mv prismagen hw
          mv shared hw
          mv node_modules hw
          mv hwbe/dist/hwbe hw
          mv hwbe/package.json hw/hwbe
          mv hwbe/.env hw/hwbe
          mv hwfe/dist/hwfe/browser hw/hwfe

      - name: Deploy
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: hw
          rm: true
          target: '/var/www/hw'
          strip_components: 1

      - name: HWBE - Database migration
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /var/www/hw
            npm run hwbe:prisma:migrate:deploy

      - name: HWBE - pm2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /var/www/hw
            pm2 delete hwbe || true
            pm2 start hwbe/src/main.js --name hwbe --update-env --cwd /var/www/hw/hwbe

      - name: HWBE - Upload sourcemaps
        working-directory: hwbe
        run: |
          npx @sentry/cli releases new -p $SENTRY_PROJECT "${{ github.sha }}"
          npx @sentry/cli sourcemaps upload hwbe/dist/hwbe/src \
            --project $SENTRY_PROJECT \
            --release "${{ github.sha }}" \
            --rewrite
          npx @sentry/cli releases finalize "${{ github.sha }}"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'hot-wizards'
          SENTRY_PROJECT: 'hwbe'

      - name: HWFE - Upload sourcemaps
        working-directory: hwfe
        run: |
          npx @sentry/cli releases new -p $SENTRY_PROJECT "${{ github.sha }}"
          npx @sentry/cli sourcemaps upload dist/hwfe/browser \
            --project $SENTRY_PROJECT \
            --release "${{ github.sha }}" \
            --rewrite
          npx @sentry/cli releases finalize "${{ github.sha }}"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'hot-wizards'
          SENTRY_PROJECT: 'hwfe'

      - name: HWFE - Sitemap generation
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /var/www/hw
            npx sitemap-generator-cli https://hotwizards.net --output ./hwfe/sitemap.xml
