name: Build and deploy Hot Wizards Frontend

on:
  push:
    branches:
      - master
    paths:
      - "hwfe/**"
      - "shared/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  build-and-deploy-hwfe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -w @hw/hwfe

      - name: Generate sitemap
        working-directory: hwfe
        run: npx sitemap-generator-cli https://hotwizards.net --output dist/hwfe/browser/sitemap.xml

      - name: Cleanup
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: rm -rf /var/www/hwfe/*

      - name: Deploy
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "hwfe/dist/hwfe/browser/*"
          target: "/var/www/hwfe"
          strip_components: 4